### ISSUE TITLE
\some

### ISSUE THREAD

**Issue by davidcok** [JavaModelingLanguage/RefMan#10]
Extracting this thread out of Issue#8.

I'm generally in favor of the \some quantifier (under some name and syntax). But a question: is it deterministic? In the given example

//@ ensure (\some int i; i > 0 && i < 3) == 1 || (\some int i; i > 0 && i < 3) == 2

I would think that the value of a \some expression can be any value that satisfies the predicate, here either 1 or 2, *non-deterministically*.
In the above the first \some could have a value 2 and the second the value 1, making the predicate false.
Perhaps what is intended is something like

\let k = (\some int i; i > 0 && i < 3); (k==1 || k==2)

or perhaps, to avoid extra trivial bindings, allow an extra expression in which the 'i' is in scope:

(\some int i; i > 0 && i < 3); i ==1 || i ==2)

Perhaps even an else value: (\some int i; i > 0 && i < 3); i ==1 || i ==2 \else false)

And (\some T k; p(k); e(k)) is well-defined iff (\exists T k; p(k)) is well-defined and true and and (\forall T k; p(k) ==> WD[e(k)]) is true.

**Comment by leavens** [comment]
Hi Mattias, David, and all,

I am opposed to changing the name \exists to \some, as I don't see a good argument for such a breaking change.

Mattias, in Java it is not the case for float and double that NaN == NaN, sigh.  Nevertheless (1) should be true always, it is just Java that is weird in this way.  I agree that (2) and (3) should hold.


        Regards,

        Gary T. Leavens
        329 L3Harris Center
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens phone: +1-407-823-4758
        ***@***.******@***.***>

**Comment by davidcok** [comment]
Gary,

1) No one is proposing replacing \exists with \some. Rather the \some quantification returns a value that satisfies the predicate, whereas \exists returns true if there is a value that satisfies the predicate.

2) Yes, I understand your (Mattias) point about the logic of \some terms. But that does provoke further questions. How much the same or different can the terms be before they are 'required' by the logic? I presume if one can be transformed to the other by substitution of equals, then they are equal. But how do you induce SMT to get this result. I expect that the SMT equivalent of assert (\some int j; phi(j)) == (\some int k; phi(k)) would be
int j,k;
assume phi(j);
assume phi(k);
assert j == k;
which I don't think SMT would prove if phi allowed multiple values.

3) Gary - regarding NaN == NaN. There should be a separate thread on FP semantics. But I think we have to come to the conclusion that == in logical (JML) statements is not the same as == in Java, at least for FP values.

**Comment by mattulbrich** [comment]
> Mattias, in Java it is not the case for float and double that NaN == NaN, sigh.

Gary, yes, right, arg. Didn't think of that. But, as David says, let's discuss elsewhere.

>  But how do you induce SMT to get this result.

Good question, indeed. Your approach is sound, but incomplete wrt. 3 (what I called extensionality).
In KeY (and similar) we have interaction to deal with that. One can at any rate add
`(∀x. phi(x) ⟷ ∀x. phi'(x)) -> j == k` to the SMT output ... for any pair of Hilbert-terms.
Granted, quadratically many quantifiers is not the most attractive of encodings. But I think it could grasp the meaning.

**Comment by leavens** [comment]
Hi David and all,

Ah, sorry for my confusion about \some. I think then that \choose might evoke more of the right intuition for what is intended.

I don't know enough to have a definite opinion about the encoding of the choice operator in SMT...


        Regards,

        Gary T. Leavens
        329 L3Harris Center
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens phone: +1-407-823-4758
        ***@***.******@***.***>

**Comment by mattulbrich** [comment]
I have checked with Isabelle to compare. There, the some operator is extensional in the above sense:
![image](https://user-images.githubusercontent.com/17046629/144309166-6b0a6542-fd4f-4e53-ab1f-1c3bf2d74669.png)
(from: https://isabelle.in.tum.de/library/HOL/HOL/Hilbert_Choice.html)

**Comment by davidcok** [comment]
Writing the (quadratic) number of extensional axioms is additionally complicated by the terms appearing in different local environments and capturing different sets of local variables.

**Comment by mattulbrich** [comment]
Regarding the enconding, I assume that `p((\some x; q(x)))` is equivalent¹ to `(\forall x; q(x); p(x))`.
Hence, I think we cannot get away with a skolemisation like David suggests in all cases.

¹ perhaps modulo wellformedness issues.

**Comment by leavens** [comment]
Hi Mattias and all,

That is interesting.


        Regards,

        Gary T. Leavens
        329 L3Harris Center
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens phone: +1-407-823-4758
        ***@***.******@***.***>

**Comment by davidcok** [comment]
Or it could be equivalent to (\exists x; q(x); p(x)).

**Comment by wadoon** [comment]
> I think then that \choose might evoke more of the right intuition for what is intended. 

Note, that [model programs already have an nondeterministic choice](https://www.cs.ucf.edu/~leavens/JML/jmlrefman/jmlrefman_15.html#SEC188) using the keyword `choose`, which does not have the same semantics as `\choose`/`\some`.

**Comment by leavens** [comment]
Hi Alexander, Mattias, David, and all,

> > I think then that \choose might evoke more of the right intuition for what is intended.

> Note, that model programs already have an nondeterministic choice using the keyword choose, which does not have the same semantics as \choose/\some.

The backslash would differentiate \choose from the choose keyword in the nondeterministic choice statement.  So I don't see this as a problem.

Using nondeterministic choice statements would allow one to implement various kinds of nondeterminism...

        Regards,

        Gary T. Leavens
        329 L3Harris Center
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens phone: +1-407-823-4758
        ***@***.******@***.***>

**Comment by leavens** [comment]
Assuming we can call the quantifier \choose, and assuming that a translation to SMTLIB is given, I am okay with putting this in JML.

**Comment by mattulbrich** [comment]
I'd still favour `\some`, but can also live with `\choose`.

There is no direct translation of these expressions into SMTLIB since the language does not support binders. But there is a complete and correct encoding into SMTLIB. For efficiency reasons one would probably sacrifice completeness from time to time.

**Comment by wadoon** [comment]
I would also favour `\some`. Mainly, because `choose` is already used differently, and similar things should have related semantics.

**Comment by mattulbrich** [comment]
> I would also favour `\some`. Mainly, because `choose` is already used differently, and similar things should have related semantics.

In this respect: I'd say that `choose` and `\choose` would both have the same semantics: "demonic choice" meaning that correctness depends on correctness for any value or statement respectively chosen from a set of possibilities.

I think
````
ghost b;
choose set b=true or set b=false;
````

is actually equivalent to

````
ghost b = (\some boolean x; true);
````

So: I'd still favour \some, but can also live with \choose.

**Comment by leavens** [comment]
I prefer \choose still, as to me \some sounds like it could be an existential quantifier.

**Comment by mattulbrich** [comment]
Let's make it `\choose` then. David@davidcok ?

**Comment by davidcok** [comment]
I'm OK with either, but would use \choose if it were up to me. But one more question on the semantics.

Given
```
ensures \result == (\choose int k; true; 1 <= k <= 2);
int m() {
  if (randomChoice()) return 1; else return 2;
}
```

I would consider the postcondition not valid (not always true). The ensures predicate must be true no matter which choice \choose makes (as in 'demonic choice'). Is that correct?

**Comment by leavens** [comment]
So I think we all are okay with \choose...

David, you are right about the method, it's not correct, since it doesn't guarantee that the postcondition is true. The "demonic" choice means that the choices can work against the program being correct, so the randomChoice could return 1 and then \choose could pick 2 (demonically), making the postcondition false.

**Comment by mattulbrich** [comment]
I'd say your answer is correct whereas the method isn't :-P

Moreover, I don't know if choose really needs two compartements. For me,

     (\choose T var; predicate)

would suffice.

**Comment by leavens** [comment]
But the syntax requires another semicolon, I believe, like:

`(\choose T var;; predicate)`

**Comment by davidcok** [comment]
The syntax should be the same as the other quantifiers, in which the range expression is optional. So the alternatives are

(\Q T v; range; expression) -- somewhat backwards incompatible

(\Q T v; [ range ; ] expression )  -- range permitted but optional -- current JML

(\Q T v; expression ) -- very backwards incompatible and harder for RAC

I prefer the middle one, not happy with the first, very not OK with the last.

**Comment by mattulbrich** [comment]
> I prefer the middle one, not happy with the first, very not OK with the 
> last.

Middle is very much ok.

-- 
Dr. Mattias Ulbrich ***@***.***>
Application-oriented Formal Verification (Prof. B. Beckert)
Institute of Theoretical Informatics     formal.iti.kit.edu
KIT - Karlsruhe Institute of Technology         www.kit.edu

**Comment by davidcok** [comment]
Allows the extra ; but does not require. I should have written

(\Q T v; [ [ range ] ; ] expression )

**Comment by davidcok** [comment]
Settled then.

**Comment by leavens** [comment]
That is fine with me.
