### ISSUE TITLE
\hence_by

### ISSUE THREAD

**Issue by davidcok** [JavaModelingLanguage/RefMan#24]
Gary - the old DRM says

The hence_by statement is used to record reasoning when writing a proof by intermittent assertions. It would normally be used between two assert statements (see section 13.3 Assert Statements) or between two assume statements (see section 13.4.1 Assume Statements).

In actual practice, how would this be different than just assuming the hence_by expression? In both cases the expression would be some tautology that the solver can't figure out on its own. hence_by has the same soundness problems as assume. Is there a connotation difference that recommends a distinct name?

[ We should find a better word than 'intermittent' ] (@leavens)

**Comment by wadoon** [comment]
I am not sure whether we should keep `\hence_by` in the ref manual, as it is just support for the verification tool. In a different issue, we had the tendency against proof commands and hints in JML. 

On the other side, I would love to have a language in which I can explain to KeY why I am right, and hence the program is correct. But further research are required to get there.

**Comment by leavens** [comment]
Hi Alexander, David, Mattias,

Yes, I agree that, following what I said earlier about not recording proof details, we should probably delete hence_by from JML.  I doubt that anyone will miss it.


        Regards,

        Gary T. Leavens
        329 L3Harris Center
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens phone: +1-407-823-4758
        ***@***.******@***.***>

**Comment by davidcok** [comment]
OK. Resolved. hence_by is deprecated. You can use assume to help a proof along if you want.
