### ISSUE TITLE
deprecate forall ?

### ISSUE THREAD

**Issue by davidcok** [JavaModelingLanguage/RefMan#33]
Now that we have \choose (aka \some)
we can write in a specification case: old T e = (\choose T x; P(x));
which I think would be entirely equivalent to 
forall T e;
requires P(e);
and as no one has claimed ever having needed forall, can we simplify matters by dropping it from JML?

**Comment by mattulbrich** [comment]
See also #8: In a nutshell, let us keep `old` and drop `forall`.
Agreed.

**Comment by mattulbrich** [comment]
In #8 Gary writes:

> I think that deprecating "forall" would be sensible.

I think we have a consensus here.
