### ISSUE TITLE
Deprecate the keywords field, method and constructor

### ISSUE THREAD

**Issue by davidcok** [JavaModelingLanguage/RefMan#45]
Classic JML defines the keywords field, method and constructor. In the grammar they are like pseudo modifiers.
Though the grammar defines them, there is no discussion of them in the DRM.
I've never implemented or used them, nor can I think of a use-case for them.

I advocate deprecating them.

**Comment by mattulbrich** [comment]
+1

**Comment by leavens** [comment]
These were originally intended to help with parsing, but if they are not needed (as they appear not to be) then I am also fine with deprecating them.
