### ISSUE TITLE
.java and .jml files

### ISSUE THREAD

**Issue by davidcok** [JavaModelingLanguage/RefMan#5]
History: JML used to allow about 6 different specification files to be associated with a .java or .class file, with different suffixes. All these files were supposed to be combined somehow to yield the specs for a class. At some point we simplified this to have just .jml files in addition to .java and .class files.

Remember that the purpose of a .jml file is to (1) give specs to a .class file when there is no .java file (e.g. a library) and (2) provide specs for a .java file when the .java file may not be modified (as I have encountered when working with industrial code) and (3) to 'overwrite' specifications in the .java file if they need to be embellished or corrected.

That said, most of the time specs for existing source code are placed right in the .java file.

If there is no .java file for a class, the meaning is clear: the specifications are in the .jml file for the class; if any Java member of the class is not declared in the .jml file, that member gets a default specification.

If there is a .java file and no .jml file then any JML specifications must be in the .java file along with the Java source code. 

The question raised here is what is the behavior if there is both a .java and a .jml file. 

Consider first a class member with a declaration in the .jml file (and by necessity also in the .java file) . Along with simplification mentioned above, we also decided not to do any 'merging' of specifications (with associated complex merging rules). So in this case, the spec in the .jml file takes precedence over the the one in the .java file and the one in the .java file is silently ignored; this is the case even if the spec in the .jml file is a default one because there is no explicit spec.

But there is a question: **must any JML annotation in the .java file be type-correct, even if it is ignored?**

The second question is this. **What is the behavior in the situation where there is both a .java and a .jml file and a Java or JML member (e.g. a ghost field or model method) is declared in just  in  the .java file?**

There are two options:

a) If there is a .jml file at all it replaces all the specs in the .java file. Any specs in the .java are ignored. Implicit declarations (with default specs) are added to the .jml file where the .jml file is missing members that are declared in the .java file (just as they are if there is a .class file and no .java file).

or

b) specs in .jml replace those in .java on a member by member basis. If the .jml file declares a member, any associated specs in the .jml file are used; if the .jml file does not declare a member, any specs in the .java file are used. Presumably this would also mean that any class-level specs in the .jml file (e.g. invariants, all ghost fields, model methods) replace any in the .java file.

I vote for (a)---it is just simpler. If any specs that are in the .java file need to be retained they must be copied into the .jml file. But with (b) one must keep looking in both files to be sure what the net spec is, so there is still some 'merging' that needs doing. Plus it is harder to just replace the specs in the .java file with a completely different approach.

**Comment by drcok** [comment]
Comment to test email

**Comment by mattulbrich** [comment]
My vote is for (a).

The meaning is way clearer. If there is a `.jml` file then it contains the JML specifications and the `.java` file contains the code even if that means ignoring JML comments in the `.java` file.
If there is no `.jml` file, the sources may include the JML specifications.

I think for transparency, a warning should be issued, however, when loading.

Moreover, I think that a `.jml` file needs not repeat all declarations if there is a `.java` file. JML must not contain more declarations than the Java sources, but need not repeat everything. There would be default contracts if a method is not mentioned.

This answers the above questions as follows: In presence of a `.jml` file with same name prefix, JML annotations in the `.java` file are Java comments and need not/must not be parsed. [They might be legacy specs from a different tool or very old JML dialect]. Java entities may be declared in Java only, but may be repeated in JML. They must not only occur in JML. JML entities can only occur in JML.

A class may also only be represented as a `.jml` entity. There are tools which would not like to parse `.class` files and rely on the information contained in `.jml` files for the specification of libraries.

I assume the following it true: Methods must not contain bodies in `.jml` files (also if they are not `abstract`).

**Comment by wadoon** [comment]
For simplicity, I tend to (a).  

But I could also imagine an option (c): 

> Separated specification (in an `.jml` file) extends the specification conservatively.

Examples:

1. If I define a contract in `.jml` it is added as one possible contract to the contract. All contracts defined in `.java` remain available.
2. Invariants defined in `.jml` are added to the class. 

In my head, I like to think about `.jml` as an extension or inheritance of the Java class. 
Not as a real inheritance, more on a virtual level. Therefore, the introduced specification 
in `.jml` follow the inheritance rules of JML.

--- 

One question regarding `jml` files: 

I looked into the [ref man](https://www.cs.ucf.edu/~leavens/JML/jmlrefman/jmlrefman_17.html) and notice that `.jml` are only for body declarations. 

If I add/replace a JML contract via `.jml`, is there also a way to replace the loop invariants which may require to proof this method? Otherwise, `.jml` files are only usable for the specification of methods which I want to use, and not those one I want to proof.

**Comment by davidcok** [comment]
> On Nov 26, 2021, at 11:12 AM, Alexander Weigl ***@***.***> wrote:
> 
> 
> For simplicity, I tend to (a).
> 
> 

We’re all in agreement then
> But I could also imagine an option (c):
> 
> Separated specification (in an .jml file) extends the specification conservatively.
> 
> Examples:
> 
> If I define a contract in .jml it is added as one possible contract to the contract. All contracts defined in .java remain available.
> Invariants defined in .jml are added to the class.
> In my head, I like to think about .jml as an extension or inheritance of the Java class.
> Not as a real inheritance, more on a virtual level. Therefore, the introduced specification
> in .jml follow the inheritance rules of JML.
> 
> 

We previously had a kind of merging of this sort. But it was complicated and not very useful. For the rare occasions when .jml and .java files (with specs of its own) are present, it is usually because the .jml needs to correct the .java specs, or to try a whole new approach. So merging just made a mess.

> 
> One question regarding jml files:
> 
> I looked into the ref man <https://www.cs.ucf.edu/~leavens/JML/jmlrefman/jmlrefman_17.html> and notice that .jml are only for body declarations.
> 
> If I add/replace a JML contract via .jml, is there also a way to replace the loop invariants which may require to proof this method? Otherwise, .jml files are only usable for the specification of methods which I want to use, and not those one I want to proof.
> 
> 
No there isn’t, nor to replace any of the other statement specs — all of which are seen as means to help the prover verify the implementation body.

But you are correct that a tweak to the postconditions might also need a corresponding tweak to loop invariants. It could be possible to allow naming predicates in the methods specs and use those names in body statement specs, but even that does not quite accomplish what is needed. For example, loop specs might be a \forall up to the loop index, so that the postcondition can be the same \forall up to say an array length, so some parameterization would be needed. A better and more general approach would be inferring the needed loop invariants from the postcondition, but that a is certainly not easy.

**Comment by leavens** [comment]
I'm agreeable to (a) provided that whenever there are JML specifications in both the .java and .jml files, then a warning is given to the user that the specifications in the .java file are all ignored.

**Comment by davidcok** [comment]
That would be a recommendation to tools, but OpenJLM can certainly do it.

**Comment by mattulbrich** [comment]
We have all agreed on:

a) If there is a .jml file at all, it replaces all the specs in the .java file. Any specs in the .java are ignored. Implicit declarations (with default specs) are added to the .jml file where the .jml file is missing members that are declared in the .java file (just as they are if there is a .class file and no .java file).
