### ISSUE TITLE
JML Syntax

### ISSUE THREAD

**Issue by davidcok** [JavaModelingLanguage/RefMan#6]
Per the previous discussions by email, I have revised the JML Syntax chapter. Here it is attached for comment.
[JML_Syntax.pdf](https://github.com/JavaModelingLanguage/RefMan/files/7613927/JML_Syntax.pdf)

**Comment by wadoon** [comment]
Thank you for the revision. I have only minors:

* Page 28.
   
   > * character sequences matching \[a-zA-Z]+ are valid identifiers. Examples are \result and \type .
   
   `\[` could be misread as an escaped opening square bracket. 

* Page 31. 

    > The JML annotation comments in the sequence may be any mix of line or block comments.
 
   This should be refined, the sequence spans over Java white spaces and comments. I would consider the following as valid:

  ```
  //@ ensures 
  // A really useless post-condition
  //@                   true;
  ```   

* Page 32
  * > modifiers (§??) — ...
   
    There is a border case: Enumeration declaration (aka enum contants) are only allowed to have annotations, and not modifier (according to JLS). I am trying to think about the necessary of modifier for these. Would following make sense?

    ```
    enum E {
       /*@ pure */ FOO() {
          // pure body declarations...    
       }; 
    }
    ```

  * > field specifications (§??) — these are placed in conjunction with a field declaration
 
    It this case not considered under the body declarations?

  * > Thus the grammatical units of JML specifications are single-word tokens (modifiers and keywords), punctuation (one or 
    > more sequential non-alphanumeric characters), and clauses, which themselves begin with keywords.

    I could not follow, where the grammatical units plays comes in. Are the *grammatical units* the starting symbol of the grammar?

  * It should be stated:  "Misplaced JML annotations should result at least into a warning."
 

* Page 35
  > `<jml-identifier> ::= [\][_a-zA-Z]+`

  Are numbers in JML identifiers forbidden (e.g, \select2)?  I would set the rule to 

  ``` 
  <jml-identifier> ::= [\] <java-identifier>
  ```

**Comment by wadoon** [comment]
I re-post my proposal for the name conflict in #7.

**Comment by davidcok** [comment]
Thanks for the comments. I added responses here and made some corrections & clarifications in the text.

> On Nov 29, 2021, at 7:33 PM, Alexander Weigl ***@***.***> wrote:
> 
> 
> Thank you for the revision. I have only minors:
> 
> Page 28.
> 
> character sequences matching [a-zA-Z]+ are valid identifiers. Examples are \result and \type .
> \[ could be misread as an escaped opening square bracket.
> 
> \
I put the backslash in its own square bracket pair to conform to regular expression grammar
> 
> Page 31.
> 
> The JML annotation comments in the sequence may be any mix of line or block comments.
> 
> This should be refined, the sequence spans over Java white spaces and comments. I would consider the following as valid:
> 
> //@ ensures 
> // A really useless post-condition
> //@                   true;
Agreed. I state elsewhere that the sequence permits intervening discarded Java tokens
> 
> Page 32
> 
> modifiers (§??) — ...
> 
> There is a border case: Enumeration declaration (aka enum contants) are only allowed to have annotations, and not modifier (according to JLS). I am trying to think about the necessary of modifier for these. Would following make sense?
> 
> enum E {
>    /*@ pure */ FOO() {
>       // pure body declarations...    
>    }; 
> }
I was not aware of this, but I concur that the JLS is as you say. However, (a) there are annotations for each of the JML modifiers that could be used and (b) we can define the grammar for enums in JML to allow JML annotations that are JML modifiers to precede declarations in the body of an enum. So I don’t think this is a problem, just something to be remembered in writing the grammar for enums.
> 
> field specifications (§??) — these are placed in conjunction with a field declaration
> 
> It this case not considered under the body declarations?
> 
> 
In and maps clauses immediately follow field declarations.
> 
> Thus the grammatical units of JML specifications are single-word tokens (modifiers and keywords), punctuation (one or
> more sequential non-alphanumeric characters), and clauses, which themselves begin with keywords.
> 
> I could not follow, where the grammatical units plays comes in. Are the grammatical units the starting symbol of the grammar?
> 
> 
Revised to remove the use of “grammatical units"
> 
> It should be stated: "Misplaced JML annotations should result at least into a warning."
> 
> 
Done
> 
> Page 35
> 
> <jml-identifier> ::= [\][_a-zA-Z]+
> 
> Are numbers in JML identifiers forbidden (e.g, \select2)? I would set the rule to
> 
> <jml-identifier> ::= [\] <java-identifier>

OK, though in practice, users cannot introduce new jml-idenrtifiers and all the defined ones are alphabetic (and ASCII)

**Comment by davidcok** [comment]
It did not take much to revise my parser to concatenate adjacent comments. However, I see some ramifications.

Error recovery is poorer. Before the parser could use the end of a JML line annotation to resynch the parser if there was an error in the line. Now the parser has a tendency to not report an error until it is in the next comment, which makes for more confusing error messages.

A good example is a missing semi-colon at the end of a clause. Before this change, if the missing semi-colon was right at the end of a JML annotation, it was easily detected and recovered -- so much so that I considered suggesting that semicolons be optional. Now a missing semicolon, which may not be one, is not spotted until the next line. And then it is not known what the problem is -- missing semicolon or missing operator etc.

For example

//@ requires a != null   // no missing semicolon here
//@     && b != null / missing semicolon here, but not known until 'ensures' -- and might be just a missing &&
//@ ensures true;

**Comment by leavens** [comment]
Hi David and all,

That is very interesting. I do typically write specifications where the next line is where the operator in a long expression is written, like the first 2 lines of your example. But I can see the problem with syntax error messages and error recovery.

I think we have to weigh the pain of worse syntax error recovery and messages against the pain of a more complex rule for JML annotation comments, especially for beginners.  My feeling is that beginners would be more confused about the rule for JML annotation comments and thus it may indeed be better to suffer the pain of poor error messages and error recovery from the concatenation rule.

        Regards,

        Gary T. Leavens
        329 L3Harris Center
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens phone: +1-407-823-4758
        ***@***.******@***.***>

**Comment by davidcok** [comment]
I’m not objecting to the newly agreed-upon syntax. Just pointing out a downside.  Also in something like

//@ invariant a
  // java comment
  // more java comment
  // even more java comment
//@ invariant b ;

The failure to end the first invariant is not discovered until several lines later.
However with some work, I think the common case of forgetting a semicolon — finding an identifier on a subsequent line instead — can be recognized and reported sensibly.

As always — implementing good error reporting in a parser is time-consuming.

- David

**Comment by wadoon** [comment]
On your example, our tool would complain that `invariant` (IDENTIFIER) is not an operator (`+`, `-`, etc.) before it would complain on the semi-colon. 

```
//@ invariant a
  // java comment
  // more java comment
  // even more java comment
//@ invariant b ;
```

Writing good error message or bail-out strategies in a parser is hard.

**Comment by wadoon** [comment]
Here is another example for strange parser cases; issue [KeY-1630](https://git.key-project.org/key/key/-/issues/1630). 

```
class A {
	void m(int i) {
		/*@ loop_invariant true;
		  @ ensures 3 != 2;
		  @ decreases 0;
		  @*/
		while(i>0) i--;
	}
}
```
The JML annotation text is parsed by KeY surprisingly w/o errors. This arise from the difference of the ideal to the effective grammar. And also, the end of a JML comment has no semantical meaning: it does not close any "grammatical unit". 

KeY sees two JML annotation entities in JML comment: 

1. A loop specification with one loop invariant 
2. A block contract with two clauses. 

The error can only be found after parsing. 

In KeY, we have loop and block contract. The first one is introduce with `loop_contract`, the second one with a modifier or a clause. Both are internally not distinguishable, and therefore KeY accepts this comment.

**Comment by davidcok** [comment]
@leavens @mattulbrich 
Leaving the issue of conflicting names to Issue#7, can we resolve this current issue:

- we allow clauses (but not tokens) to spill over line annotations, so all that matters is the token stream (a change to OpenJML)
- we allow nested annotation comments, acknowledging Mattias's small discomfort, because of the readability and editing advantages of putting Java comments in, for example, method specifications and being able to conditionally comment parts of a spec without having to convert between block and line annotations. I can say that I would only ever use them in public specs (e.g. system library) as one level deep to enable or disable particular parts of a long spec (or to insert Java comments).

**Comment by mattulbrich** [comment]
agreed.

**Comment by wadoon** [comment]
I implemented these definitions in jmlparser, and they are working fine.

**Comment by leavens** [comment]
Hi David, Mattias,

Yes, I agree with these (allowing clauses but not tokens to be split over multiple line annotations and allowing nested annotation comments).


        Regards,

        Gary T. Leavens
        329 L3Harris Center
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens phone: +1-407-823-4758
        ***@***.******@***.***>

**Comment by davidcok** [comment]
OK. Closing this issue as agreed.
